parent_dir = "exp/yeast_me2/CTGAN"
real_data_path = "Dataset-all/yeast_me2/"
dataname = "yeast_me2"
ir = 28.1
seed = 0
device = "cuda"
task_type = "binclass"
num_classes = 2
num_numerical_features = 8
num_categorical_features = 0
num_categorical = []
model_type = "transformer"
X_num_columns = [
    "mcg",
    "gvh",
    "alm",
    "mit",
    "erl",
    "pox",
    "vac",
    "nuc",
]
X_cat_columns = []
y_column = [
    "localization_site",
]

[train_params]
epochs = 100000
batch_size = 1000

[sample]
seed = 0
num_samples = 1038

[eval.Transform]
seed = 0
normalization = "minmax"
cat_encode_policy = "Ordinal"
y_policy = "Ordinal"
y_plus1 = false
