parent_dir = "exp/bean/CTGAN"
real_data_path = "Dataset-all/mammography/"
dataname = "mammography"
ir = 25.07
seed = 0
device = "cuda"
task_type = "binclass"
num_classes = 2
num_numerical_features = 6
num_categorical_features = 0
num_categorical = []
X_num_columns = [
    "0",
    "1",
    "2",
    "3",
    "4",
    "5",
]
X_cat_columns = []
y_column = [
    "target",
]

[train_params]
epochs = 20000
batch_size = 1000

[sample]
seed = 0
num_samples = 7828

[eval.Transform]
seed = 0
normalization = "None"
cat_encode_policy = "Ordinal"
y_policy = "Ordinal"
y_plus1 = false
