parent_dir = "exp/buddy/CTGAN"
real_data_path = "Dataset-all/buddy/"
dataname = "buddy"
seed = 0
ir = 213.02
device = "cuda"
task_type = "binclass"
num_classes = 2
num_numerical_features = 2
num_categorical_features = 5
num_categorical = [
    4,
    56,
    20,
    10,
    4,
]
X_num_columns = [
    "length(m)",
    "height(cm)",
]
X_cat_columns = [
    "condition",
    "color_type",
    "X1",
    "X2",
    "breed_category",
]
y_column = [
    "pet_category",
]

[train_params]
epochs = 100000
batch_size = 1000

[sample]
seed = 0
num_samples = 13185

[eval.Transform]
seed = 0
normalization = "minmax"
cat_encode_policy = "Ordinal"
y_policy = "Ordinal"
y_plus1 = false
