parent_dir = "D:/Study/自学/表格数据生成/LogiCoTab-LP-GAT/exp/buddy/CoTable"
real_data_path = "D:/Study/自学/表格数据生成/LogiCoTab-LP-GAT/Dataset-all/buddy/"
dataname = "buddy"
task_type = "binclass"
num_classes = 2
num_numerical_features = 2
num_categorical_features = 5
num_categorical = [
    4,
    56,
    20,
    10,
    4,
]
model_type = "transformer"
seed = 0
device = "cuda"
X_num_columns = [
    "length(m)",
    "height(cm)",
]
X_cat_columns = [
    "condition",
    "color_type",
    "X1",
    "X2",
    "breed_category",
]
y_column = [
    "pet_category",
]

[Transform]
seed = 0
normalization = "quantile"
cat_encode_policy = "Ordinal"
y_policy = "Ordinal"
y_plus1 = false

[VAE]
lr = 0.005
epoch = 15000
wd = 0
d_token = 5
token_bias = true
n_head = 1
factor = 32
num_layers = 2
batch_size = 1024
scheduler_fac = 0.982
scheduler_patience = 5
margin = 5

[model_params]
is_y_cond = true
d_in = 35
dim_t = 128
feedforward_layer = [
    1024,
    2048,
    1024,
]
depth = 2
ff_dropout = 0.0
activation = "reglu"
bert = "prajjwal1/bert-tiny"
bert_max_length = 9

[LP]
lp_k=30
lp_alpha=0.9
lp_seed_ratio=0.2
lp_max_iter=200
lp_boundary_lambda=1.0
alpha_pos=0.00
alpha_neg=0.85
flip_margin=0.1


[Train]
epochs = 400
focal_alpha = 0.25